### ISSUE TITLE
Compiling with project files result in a faulty .dll file

### ISSUE THREAD

**Issue by kingocd** [jsgonsette/Wizium#4]
Hello, thanks for this great project!

I was trying to add a few functions to the c++ code, but I noticed that I can't use the dll I get out of compiling the projects in the Projects folder.

If I try to use the resulting dll, I get the following error message when trying to run testWizium.py:

Traceback (most recent call last):
  File "C:\Users\Xeon\source\repos\TxtToJson\Wizium-master\TestWizium.py", line 263, in <module>
    example_1()
  File "C:\Users\Xeon\source\repos\TxtToJson\Wizium-master\TestWizium.py", line 168, in example_1
    wiz = Wizium (os.path.join (os.getcwd (), PATH),alphabet="abcdefghijklmnopqrstuvwxyz")
  File "C:\Users\Xeon\source\repos\TxtToJson\Wizium-master\libWizium.py", line 129, in __init__
    api = proto ((func_name, self._dll), None)
AttributeError: function 'WIZ_Init' not found
Exception ignored in: <function Wizium.__del__ at 0x00000141AC6851F0>
Traceback (most recent call last):
  File "C:\Users\Xeon\source\repos\TxtToJson\Wizium-master\libWizium.py", line 156, in __del__
    self._wiz_destroy_instance ()
  File "C:\Users\Xeon\source\repos\TxtToJson\Wizium-master\libWizium.py", line 445, in _wiz_destroy_instance
    instance = ctypes.c_ulonglong (self._instance)
AttributeError: 'Wizium' object has no attribute '_instance'

However this error is not present with the sample dll you provided.

I have tried:

Using VS2019 and setting sdk to 10.17134 and platform tools to v141
Using VS2017 
Using cmake

and couldn't make it work.

**Comment by jsgonsette** [comment]
Hello, 

Seems the problem is the missing 'WIZ_Init' function, indicating it is not exported well from the library.
In the file `libWizium.h`, try to update line 38 with that one:
```
#if defined(_WIN64) || defined (_WIN32)
```
In order to cope a bit better with x86 or x64 build systems.

**Comment by kingocd** [comment]
Thank you very much! Was left scratching my head for a week.

This was the solution.

**Comment by jsgonsette** [comment]
Nice, I just pushed an update to correct this problem.
